### ISSUE TITLE
[v5] WARNING: Invalid cookie header: 'Invalid 'expires' attribute'

### ISSUE THREAD

**Issue by marysia16122** [reportportal/agent-java-testNG#100]
**Describe the bug**
I have WARNING in my java autotest console, when I run tests using report portal

`апр. 16, 2020 2:29:21 PM rp.org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: AWSALB=P7cqG8g/K70xHAKOUPrWrG0XgmhG8GJNinj8lDnKVyITyubAen2lBr+fSa/e2JAoGksQphtImp49rZxc41qdqUGvAc67SdZHY1BMFIHKzc8kyWc1oQjq6oI+s39U; Expires=Thu, 23 Apr 2020 11:29:18 GMT; Path=/". Invalid 'expires' attribute: Thu, 23 Apr 2020 11:29:18 GMT
`

libraries(use java 13):
`  com.epam.reportportal.agent-java-testng:5.0.0-BETA-9`
`com.epam.reportportal.logger-java-log4j:5.0.0-BETA-9`

**Expected behavior**
No WARNING

Installed:
`    'analyzer': '5.0.0',`
`      'api': '5.0.0',`
`      'index': '5.0.5',`
`      'migrations': '5.0.0',`
`      'uat': '5.0.0',`
`      'ui': '5.0.0',`
`      rabbit 3.8.3`
`      pg12`
`      minio/minio:latest`
`      elk_version: 7.6.1`

**Comment by HardNorth** [comment]
Well, you can mute such messages using regular logging configuration. Just set level ERROR for packages starting with 'rp'. 

As for us, no, we are not going to disable our logging. No libraries in a whole java world do such. Why we should?

**Comment by marysia16122** [comment]
Why we cannot fix this? not switch off warning log.
