### ISSUE TITLE
Duplicate Suite name is coming for each run inside launch

### ISSUE THREAD

**Issue by shishirdwivedi2008** [reportportal/agent-java-testNG#102]
Hello Team,
For my every run , I see two suite name(duplicate) inside the launch. One is always in interrupted state and another one contains all my test cases with a log. Seems like duplicate suite name is logged into the report.
I am attaching a screenshot for the same. Do let me know if any logs are required for this.
Also, Launch contains logs for after method. As per my understanding after method logs should be inside the test method log only because after execution of after method a test case will complete.
I am also attaching a screenshot for that. Kindly advice.

![image](https://user-images.githubusercontent.com/5128761/80691484-f4f80a80-8aed-11ea-9d3b-dc0f60ac2cce.png)

![image](https://user-images.githubusercontent.com/5128761/80692142-cfb7cc00-8aee-11ea-8aed-f78be0912695.png)

**Comment by shishirdwivedi2008** [comment]
@HardNorth  I am initializing ReportPortal Listener in my pom.xml file and executing test cases using mvn clean test.
Below is a snippet of my pom.xml

 <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M4</version>
                          <configuration>
                        <suiteXmlFiles>
                            
                            <suiteXmlFile>${testNgXml}</suiteXmlFile>
                        </suiteXmlFiles>
                              <properties>
									<property>
										<name>usedefaultlisteners</name>
										<value>false</value> 
									</property>
                                  
                                   <property>
                                      <name>listener</name>
                                      <value>com.epam.reportportal.testng.ReportPortalTestNGListener</value>
                                  </property>
                              </properties>
                    </configuration>
                </plugin>

**Comment by DzmitryHumianiuk** [comment]
@shishirdwivedi2008 for RPv5 you should use agents starting with 5.x

https://bintray.com/epam/reportportal/agent-java-testng/5.0.0-BETA-9 (for TestNG 7)
https://bintray.com/epam/reportportal/agent-java-testng/5.0.0-BETA-14-TESTNG6 (for TestNG 6)

**Comment by HardNorth** [comment]
@shishirdwivedi2008 Can you provide an example project which reproduces the issue?

**Comment by HardNorth** [comment]
Abandoned
