### ISSUE TITLE
ReportPortal TestNg java is not finishing the launch in case of TestNG process interuption

### ISSUE THREAD

**Issue by the-octopus** [reportportal/agent-java-testNG#110]
I have the an issue, when the TestNg execution is interrupted or failed for some reasons , the launch is not finished. and I have to force finish the launch

**Example:** Start a testNg test from InteliJ IDEA , then stop the running from the IDEA also  before it ends testing. the issue will appear.

Could you please explain how to programmatically force finish from testNG Java client the interrupted launches.

Thanks.

**Comment by HardNorth** [comment]
Implemented in https://github.com/reportportal/agent-java-testNG/releases/tag/5.0.3
