### ISSUE TITLE
allow retry for configuration methods 

### ISSUE THREAD

**Issue by yoavgeva** [reportportal/agent-java-testNG#112]
we use IConfigurable of TestNG to retry configuration methods, the server today shows all the retries under same configuration item, we would like to be able to see the retries the same as in Test Items retries on the server, how can we use the testng-client to inform the server there is a retry for the configuration

**Comment by HardNorth** [comment]
@yoavgeva Can you please provide an example code of your project? And current behavior screenshots? I can't understand your case.

**Comment by HardNorth** [comment]
Abandoned
