### ISSUE TITLE
[v5] WARNING: Invalid cookie header: 'Invalid 'expires' attribute'

### ISSUE THREAD

**Issue by marysia16122** [reportportal/agent-java-testNG#114]
According to https://github.com/reportportal/agent-java-testNG/issues/100

I use setting in log4j2.xml:
`<Logger name="rp" level="ERROR"/>`
but it's not work for me. Can you help me?

**Comment by HardNorth** [comment]
A little bit elaboration here:
> Why you cannot fix this?

> Do not turn off logging but fix the problem that no warning in this place?

Our code operates as we expected. Such warning tells you that your server is trying to set cookies on our client. Well, actually we are not using cookies in our agents at all, your server decided to set them by itself.

Well, I actually can do something to mute this, there is a solution: https://stackoverflow.com/a/40697322/2802832
But, again, it's like hiding the fact that your servers sets us cookies, which we are not expect. And you will have to use the latest version of the agent.
> Or it's problem in my code?

It's a configuration of your server.

>I use setting in log4j2.xml:
`<Logger name="rp" level="ERROR"/>`
but it's not work for me. Can you help me?

ResponseProcessCookies uses commons-logging, to make it obey log4j2 rules you need this:
https://logging.apache.org/log4j/2.x/log4j-jcl/index.html

**Comment by HardNorth** [comment]
Fixed: https://github.com/reportportal/client-java/pull/104
