### ISSUE TITLE
V5_Could not find artifact org.aspectj:aspectjrt:pom:1.9.2 in selenium-repo (http://repo.jenkins-ci.org/releases/) for report

### ISSUE THREAD

**Issue by pprraashant** [reportportal/agent-java-testNG#139]
create mvn based project. 

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>5.0.6</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>5.0.2</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-logback</artifactId>
            <version>5.0.2</version>
        </dependency>

do mvn clean install 

with setting.xml repository setting to - http://repo.jenkins-ci.org/releases/) 

 <repository>
              <id>selenium-repo</id>
              <url>http://repo.jenkins-ci.org/releases/</url>
              <releases>
                  <enabled>true</enabled>
              </releases>
          </repository>

**Comment by HardNorth** [comment]
It is within maven central: https://search.maven.org/artifact/org.aspectj/aspectjrt/1.9.2/jar

You can exclude it if you would like to use `http://repo.jenkins-ci.org/releases/` only. The dependency is used in nested step reporting and can be removed if you are not using it.

But notice we are not obligated to use one repository or another.
