### ISSUE TITLE
How to run reportportal test for MAVEN+TESTNG+CUCUMBER.

### ISSUE THREAD

**Issue by ShanmugaPrasanth94** [reportportal/agent-java-testNG#141]
I have tried using the Testng.xml to trigger my framework. I am using Multimodule framework. When i run the testng.xml test is triggered but the Cucumber feature steps are not getting posted in the ReportPortal dashboard. Kindly help me out to resolve this.

**Comment by HardNorth** [comment]
1. Use `cucumber-testng` and implement a runner as here: https://github.com/reportportal/examples-java/blob/cucumber4-jackson-no-method/example-cucumber4/src/test/java/TestRunner.java
2. Include the latest cucumber and TestNG agents into your dependencies.
3. Use two testng.xml files: one with your TestNG tests and one with the runner. For one with TestNG tests also specify our TestNG listener: `com.epam.reportportal.testng.ReportPortalTestNGListener`

**Comment by ShanmugaPrasanth94** [comment]
If i am running my test I am getting this issue. 

io.cucumber.core.exception.CucumberException: Couldn't load plugin class: com.epam.reportportal.cucumber.ScenarioReporter

**Comment by ShanmugaPrasanth94** [comment]
@HardNorth 
Hi Still the Issue is not closed, Kindly Provide your Input on this to sort out this issue.

**Comment by HardNorth** [comment]
@ShanmugaPrasanth94 Please include correct cucumber agent, we have 4 of them.

**Comment by ShanmugaPrasanth94** [comment]
Hi @HardNorth  I am using the following dependencies. But still No luck .




      <dependency>
        <groupId>com.epam.reportportal</groupId>
        <artifactId>agent-java-testng</artifactId>
        <version>5.0.6</version>
      </dependency>

      <dependency>
        <groupId>com.epam.reportportal</groupId>
        <artifactId>agent-java-cucumber4</artifactId>
        <version>5.0.0-BETA-13</version>
      </dependency>

      <dependency>
        <groupId>com.epam.reportportal</groupId>
        <artifactId>logger-java-logback</artifactId>
        <version>5.0.2</version>
      </dependency>
    </dependencies>


  <repositories>
  <repository>
    <id>bintray</id>
    <url>http://dl.bintray.com/epam/reportportal</url>
  </repository>
  </repositories>


      <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-java</artifactId>
        <version>6.0.0</version>
      </dependency>

      
      <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-testng</artifactId>
        <version>6.0.0</version>
      </dependency>


      
      <dependency>
        <groupId>org.testng</groupId>
        <artifactId>testng</artifactId>
        <version>6.14.3</version>
      </dependency>

      
      <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-core</artifactId>
        <version>6.0.0</version>
      </dependency>

**Comment by ShanmugaPrasanth94** [comment]
@HardNorth tried Cucumber, Cucumber2, Cucumber3, Cucumber4. but still am getting the same error. Please help me on this.

**Comment by HardNorth** [comment]
@ShanmugaPrasanth94 Which version of cucumber are you using?

**Comment by HardNorth** [comment]
@ShanmugaPrasanth94 Oh, I see you are using Cucumber 6. Forget about it, we don't have such integration and I don't have any ETA when we will implement it.

**Comment by ShanmugaPrasanth94** [comment]
@HardNorth Thanks a lot for your response. Can you tell me what is the highest or the latest cucumber version supporting ReportPortal?

**Comment by HardNorth** [comment]
@ShanmugaPrasanth94 I believe we support all versions of cucumber till about 5.5, where they changed reporters again. Early versions of fifth cucumber works with cucumber4 agent.

**Comment by ShanmugaPrasanth94** [comment]
@HardNorth oh great. Thanks for your response.

**Comment by HardNorth** [comment]
Cucumber has millions of servants, it's not possible to catch their pace just with one person who also need to support 12 other agents.

**Comment by ShanmugaPrasanth94** [comment]
@HardNorth ya that's very true. Accepted. Kindly let me know once if the support for Cucumber 6 is provided. That would be a great help. Thanks.
