### ISSUE TITLE
Selenium Grid Execution with Report Portal 

### ISSUE THREAD

**Issue by vaibhavshukl12** [reportportal/agent-java-testNG#142]
Hi All.
Is there any solution in the report portal for parallel execution.
I integrated, RP with TestNG, and I implemented a grid also but I want multiple launches depends on nodes in grid how I can achieve this.
I want different launches with respective nodes.

**Comment by HardNorth** [comment]
@Vaibhavshukla08 What exact question do you have? As Dmitry said you need to implement your own agent with some custom logic if you want to report separate packages as separate launches.

Which exact clary do you want? I believe you have to examine our examples / documentation / code by yourself:
* An example of extending of a TestNG listener: https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/extension/RetriedTestReasonReporting.java
* A reporter dev guide: https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md
* Our documentation: https://reportportal.io/docs/Log-Data-in

**Comment by HardNorth** [comment]
Abandoned
