### ISSUE TITLE
Add TestClass node to report tree

### ISSUE THREAD

**Issue by MaksimShilaS** [reportportal/agent-java-testNG#145]
With agent-java-testNG I could only get tree as predefined in xml suite
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite data-provider-thread-count="30" name="Super suite">

    <listeners>
        <listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener"/>
    </listeners>

    <test name="Tests group">
        <classes>
            <class name="com.bla.TestTest"/>
            <class name="com.bla.BlaBlaClass"/>
            <class name="com.bla.GreatTest"/>
        </classes>
    </test>
</suite>

So I'll got report tree
- Launch Name
-- Super Suite
--- Tests Group
----- some test from some class
----- some another test from some class

Is there good way to see class names as tree nodes?
I didn't find any possibility to resolve this with extending TestNgService and creating custom listener
Maybe there is plans to do that?

**Comment by HardNorth** [comment]
@MaksimShilaS there is no such plans, this is the way how TestNG works.

**Comment by HardNorth** [comment]
@MaksimShilaS I'm closing this out. If you have any straight implementation which does not break current behaviour I can consider it in a pull request from you.
