### ISSUE TITLE
While running TestNG in eclipse, it opens dialog box with below error. "An internal error occurred during: Launching testfile".java

### ISSUE THREAD

**Issue by chavansatish** [reportportal/agent-java-testNG#146]
Occurred below error, while running TestNG xml file. Can you please help me.Below are the more detail regarding error.
Error: An internal error occurred during: "Launching TestNGtTutorialNew_testng.xml".
org.testng.eclipse.maven.MavenTestNGLaunchConfigurationProvider.getArguments(Lorg/eclipse/debug/core/ILaunchConfiguration;)Ljava/lang/String;
![error](https://user-images.githubusercontent.com/18119019/93975777-8e71d280-fd95-11ea-8b86-7ca55714a005.png)

**Comment by HardNorth** [comment]
Not related to our product.
