### ISSUE TITLE
Wrong RP launch structure

### ISSUE THREAD

**Issue by vzahorodnii** [reportportal/agent-java-testNG#151]
Имеем следующую структуру testng.xml файла:

![изображение](https://user-images.githubusercontent.com/75780254/101755009-1043e300-3add-11eb-99bc-e2ea7fd4517e.png)

Тестовые классы подключены через наследование базового BaseTest с аннотацией @Listeners в который подключен RP слушаетль.

В итоге при запуске тестов в репорт портал попадает лишний TestItem со статусом Interrupted.

![изображение](https://user-images.githubusercontent.com/75780254/101755053-1b970e80-3add-11eb-995e-de64734d04d2.png)

![изображение](https://user-images.githubusercontent.com/75780254/101754713-b511f080-3adc-11eb-9e75-3c4228a53c9d.png)

![изображение](https://user-images.githubusercontent.com/75780254/101754679-ac211f00-3adc-11eb-8e01-b3ff599ef9e4.png)

А так же в лог идет сообщение, что подключено 2 слушателя, при том что слушатель подключен всего один в BaseTest-e

![изображение](https://user-images.githubusercontent.com/75780254/101755243-51d48e00-3add-11eb-8020-73d882de7093.png)

Версия приложения 5.3.3
![изображение](https://user-images.githubusercontent.com/75780254/101755736-e63ef080-3add-11eb-9433-3cceb3a02b50.png)

**Comment by HardNorth** [comment]
TestNG Report Portal agent is nothing to do with that. This is a TestNG bug: https://github.com/cbeust/testng/issues/2220
I've actually implemented a simple project to reproduce: https://github.com/HardNorth/testng-two-tests-bug
If I run it with TestNG 7.3.0 (as set) it will not produces the interrupted item.

For the future, please post issues using text information (not screenshots) and English only. It will help others to find a solution.
