### ISSUE TITLE
Reportportal: Getting error for java.lang.NoClassDefFoundError: com/epam/reportportal/service/tree/TestItemTree while using with selenium + maven + testng

### ISSUE THREAD

**Issue by Mandeepsheoran** [reportportal/agent-java-testNG#152]
Hi 
I am using Selenium+testng and getting below error while running it.

 There was an error in the forked process:

java.lang.NoClassDefFoundError: com/epam/reportportal/service/tree/TestItemTree
[ERROR] at com.epam.reportportal.testng.TestNGService.<clinit>(TestNGService.java:87)
[ERROR] at com.epam.reportportal.testng.ReportPortalTestNGListener$1.get(ReportPortalTestNGListener.java:32)
[ERROR] at com.epam.reportportal.testng.ReportPortalTestNGListener$1.get(ReportPortalTestNGListener.java:29)
[ERROR] at rp.com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
[ERROR] at com.epam.reportportal.testng.ReportPortalTestNGListener.<init>(ReportPortalTestNGListener.java:37)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ERROR] at java.lang.Class.newInstance(Class.java:442)
[ERROR] at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:69)
[ERROR] at org.testng.TestNG.addListeners(TestNG.java:949)
[ERROR] at org.testng.TestNG.initializeConfiguration(TestNG.java:912)
[ERROR] at org.testng.TestNG.initializeEverything(TestNG.java:996)
[ERROR] at org.testng.TestNG.run(TestNG.java:1009)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
[ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: java.lang.ClassNotFoundException: com.epam.reportportal.service.tree.TestItemTree
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

My pom file is below:

 <groupId>com.epam.reportportal</groupId>
   <artifactId>logger-java-logback</artifactId>
   <version>5.0.3</version>
</dependency>

<dependency>
  <groupId>com.epam.reportportal</groupId>
  <artifactId>agent-java-testng</artifactId>
  <version>5.0.8-TESTNG6</version>
</dependency>

<dependency>
  <groupId>com.epam.reportportal</groupId>
  <artifactId>client-java</artifactId>
  <version>3.0.0</version>
</dependency>
<dependency>
    <groupId>com.google.inject</groupId>
    <artifactId>guice</artifactId>
    <version>4.1.0</version>
</dependency>
<dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-annotations</artifactId>
        <version>2.8.6</version>
</dependency>
	
    </dependencies>

  <repositories>
     <repository>
        <snapshots>
          <enabled>false</enabled>
        </snapshots>
        <id>bintray-epam-reportportal</id>
        <name>bintray</name>
        <url>https://dl.bintray.com/epam/reportportal</url>
     </repository>
</repositories>

I have completed listeners setting also in testng.

**Comment by HardNorth** [comment]
Where did you get this configuration?
First of all: you don't need to include client-java separately, let agent take it's own dependency. `client-java` of version `3.0.0` is way too outdated and incompatible with current agent versions.
Second: guice and jackson are redundant now.
