### ISSUE TITLE
Skipped test method has defect type select option when @BeforeClass configuration fails 

### ISSUE THREAD

**Issue by alex-i-rybkin** [reportportal/agent-java-testNG#153]
**Environment**
testng:7.1.0 
agent-java-testng:5.0.8
ReportPortal 5.3.3

When @BeforeMethod fails **there is no defect type** select option for the Skipped Test item.
![image](https://user-images.githubusercontent.com/30799266/104711324-e14b0d80-5729-11eb-9af8-4246f1c086f7.png)
When @BeforeClass fails **user can select defect type** select option for the Skipped Test item.
![image](https://user-images.githubusercontent.com/30799266/104711341-e60fc180-5729-11eb-9166-dbadad141bd5.png)

It seems that on any configuration method fail skipped methods should not have an option to select defect type.

@HardNorth mentioned that problem lies here: https://github.com/reportportal/agent-java-testNG/blob/develop/src/main/java/com/epam/reportportal/testng/TestNGService.java#L475

**Comment by HardNorth** [comment]
Fixed: https://github.com/reportportal/agent-java-testNG/releases/tag/5.0.9
