### ISSUE TITLE
Test owner and groups to test cases

### ISSUE THREAD

**Issue by mchundi** [reportportal/agent-java-testNG#157]
Hi,
How can I add test owner and groups to a test case.

**Comment by HardNorth** [comment]
@mchundi We have Attributes feature, you can use it to add metadata to your tests:
https://github.com/reportportal/client-java/wiki/Test-item-attributes

**Comment by mchundi** [comment]
Thank you.
Is there a way I can override the attributes?
I want to add tags in BeforeMethod instead of modifying each test case.

**Comment by mchundi** [comment]
I tried this https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/extension/ParametersAsAttributesTest.java
but it does not add tags to the test method

**Comment by HardNorth** [comment]
I found that usage of `buildStartStepRq(org.testng.ITestResult)` method was lost somewhere in refactorings. I returned it back but it become available only in the next release. As a workaround you can update [these lines](https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/extension/ParametersAsAttributesTest.java#L78-79) as here:
```
		protected StartTestItemRQ buildStartStepRq(final @Nonnull ITestResult testResult, final @Nonnull TestMethodType type) {
			final StartTestItemRQ rq = super.buildStartStepRq(testResult, type);
```
