### ISSUE TITLE
Failed Test cases screenshot

### ISSUE THREAD

**Issue by GopalSawant** [reportportal/agent-java-testNG#162]
How to implement listeners on failed test cases. or how to attach screenshot to report portal. Does report portal internally do that

**Comment by HardNorth** [comment]
Please look into examples: https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/extension/ScreenshotOnFailureTestExtension.java

**Comment by GopalSawant** [comment]
Hi, Thanks for the quick response.
how to implement same in framework as you will have multiple classes , and in your example everything is at one place. 
Can I make different class like listeners and every failed test case from other class will call automatically onfail

**Comment by HardNorth** [comment]
@GopalSawant We do not provide Test Automation consulting in general.
