### ISSUE TITLE
Access denied for bintray

### ISSUE THREAD

**Issue by vrakr19** [reportportal/agent-java-testNG#163]
Failed to execute goal on project CoreFramework: Could not resolve dependencies for project com.sap.he2e.framework:CoreFramework:jar:0.0.1: Failed to collect dependencies at org.uncommons:reportng:jar:1.1.4 -> org.testng:testng:jar:6.13 -> com.beust:jcommander:jar:1.66: Failed to read artifact descriptor for com.beust:jcommander:jar:1.66: Could not transfer artifact com.beust:jcommander:pom:1.66 from/to bintray (http://dl.bintray.com/epam/reportportal): Access denied to: http://dl.bintray.com/epam/reportportal/com/beust/jcommander/1.66/jcommander-1.66.pom , ReasonPhrase:Forbidden. 

How to resolve it?

**Comment by HardNorth** [comment]
Just remove the repository and ensure you have Maven Central set.
