### ISSUE TITLE
[ERROR] bad class file: /var/lib/jenkins/.m2/repository/com/epam/reportportal/commons-model/5.1.0/commons-model-5.1.0.jar(com/epam/ta/reportportal/ws/model/FinishExecutionRQ.class)

### ISSUE THREAD

**Issue by lavanyach-sailo** [reportportal/agent-java-testNG#164]
Hello,

Seeing compilation errors while running from jenkins. Using jdk 11 version.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project InforAutomation: Compilation failure
[ERROR] /var/lib/jenkins/workspace/Infor_LN/src/main/java/com/sailotech/testautomation/inforln/accelarators/TestBase.java:[54,41] cannot access com.epam.ta.reportportal.ws.model.FinishExecutionRQ
[ERROR] bad class file: /var/lib/jenkins/.m2/repository/com/epam/reportportal/commons-model/5.1.0/commons-model-5.1.0.jar(com/epam/ta/reportportal/ws/model/FinishExecutionRQ.class)
[ERROR] class file has wrong version 55.0, should be 52.0
[ERROR] Please remove or make sure it appears in the correct subdirectory of the classpath.

Kindly help on this

**Comment by HardNorth** [comment]
It looks like you overwrote our version of `commons-model` library with newer one in your build scripts (5.1.0). Our TestNG agent still use version 5.0.0: https://github.com/reportportal/agent-java-testNG/blob/develop/build.gradle#L57

Please revert to compatible `commons-model` version.
