### ISSUE TITLE
Google Analytics Connection Error

### ISSUE THREAD

**Issue by vrakr19** [reportportal/agent-java-testNG#166]
13:40:44  [36mTest_module_chrome_1  |[0m 2021-06-14 08:10:36,555 [rp-io-1] ERROR com.epam.reportportal.service.analytics.Statistics - Remote host closed connection during handshake
13:40:44  [36mTest_module_chrome_1  |[0m Exception in thread "main" java.lang.RuntimeException: Unable to complete execution of all dependencies
13:40:44  [36mTest_module_chrome_1  |[0m 	at com.epam.reportportal.service.analytics.AnalyticsService.close(AnalyticsService.java:102)
13:40:44  [36mTest_module_chrome_1  |[0m 	at com.epam.reportportal.service.LaunchImpl.finish(LaunchImpl.java:225)
13:40:44  [36mTest_module_chrome_1  |[0m 	at com.epam.reportportal.service.launch.PrimaryLaunch.finish(PrimaryLaunch.java:48)
13:40:44  [36mTest_module_chrome_1  |[0m 	at com.epam.reportportal.testng.TestNGService.finishLaunch(TestNGService.java:146)
13:40:44  [36mTest_module_chrome_1  |[0m 	at com.epam.reportportal.testng.BaseTestNGListener.onExecutionFinish(BaseTestNGListener.java:57)
13:40:44  [36mTest_module_chrome_1  |[0m 	at org.testng.TestNG.runExecutionListeners(TestNG.java:1053)
13:40:44  [36mTest_module_chrome_1  |[0m 	at org.testng.TestNG.run(TestNG.java:1015)
13:40:44  [36mTest_module_chrome_1  |[0m 	at org.testng.TestNG.privateMain(TestNG.java:1336)
13:40:44  [36mTest_module_chrome_1  |[0m 	at org.testng.TestNG.main(TestNG.java:1304)
13:40:44  [36mTest_module_chrome_1  |[0m Caused by: java.util.concurrent.TimeoutException: The source did not signal an event for 300 seconds and has been terminated.

Here Can I disable Google Analytics?

**Comment by HardNorth** [comment]
You can disable Google Analytics if you put anything int  variable into `AGENT_NO_ANALYTICS` environment variable.
