### ISSUE TITLE
HELP: Is possible to provide existing launch ID to the agent?

### ISSUE THREAD

**Issue by Drimix20** [reportportal/agent-java-testNG#168]
Hi,

I have situation, when I have paralelized jenkins jobs which run the same group (e.g. api tests), but runs them in paralel to shorten the duration of testing. I would like to report each parallel job to the one started launch in RP. I'm able to start/stop launch by Rest API, but I don't know how I can provide launch id to the agent?

Scenario:
1) Start testing job:
2) Start new launch by Rest API
3) Start subjobs
3a) Start sub-job1 with provided launch id and test results are published to the launch
3b) Start sub-job2 with provided launch id and test results are published to the launch
4) Finish started lauch by Rest API

When I use rerun option, launch is closed by each sub job and launch is marked as rerun. This is not exactly what I want.

Versions:
ReportPortal:  5.4.0
agent-java-testNG: 5.0.10-TESTNG6

Thank you.

**Comment by HardNorth** [comment]
@Drimix20 Please use `rp.launch.uuid` property and the agent version at least `5.1.4`. See: https://github.com/reportportal/client-java#parameters

And there is no support for TestNG 6 anymore.
