### ISSUE TITLE
Getting error [ERROR] java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;

### ISSUE THREAD

**Issue by mohitb01** [reportportal/agent-java-testNG#173]
I am trying to integrate TestNG framework with Reportportal. Using below dependencies but getting error [ERROR] java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;

Can anyone please help here.

Dependencies:

<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>bintray-epam-reportportal</id>
			<name>bintray</name>
			<url>http://dl.bintray.com/epam/reportportal</url>
		</repository>
	</repositories>

<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-testng</artifactId>
			<version>5.1.0-RC-1</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-log4j</artifactId>
			<version>5.0.3</version>
		</dependency>

**Using listener in testng.xml file** : <listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener" />
**TestNG version 7.4.0**
Thanks in advance,

**Comment by HardNorth** [comment]
@mohitb01 2 questions:
1. There is no any dependencies on Bintray, since it's down from May. Could you please ensure that you use correct dependency?
2. I need at least full stack trace or example project to reproduce the issue. Or even both. Since we have a whole batch of integration tests and they all pass I believe it's something unusual you do.

**Comment by mohitb01** [comment]
@HardNorth 

StackTrace:

[RemoteTestNG] detected TestNG version 7.4.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/C:/Users/mohit.bhatt/.m2/repository/com/squareup/retrofit2/retrofit/2.9.0/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:506)
	at com.epam.reportportal.service.ReportPortal$Builder.buildRestEndpoint(ReportPortal.java:454)
	at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$2(ReportPortal.java:432)
	at java.base/java.util.Optional.map(Optional.java:254)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:432)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:407)
	at com.epam.reportportal.testng.TestNGService.<clinit>(TestNGService.java:88)
	at com.epam.reportportal.utils.MemoizingSupplier.get(MemoizingSupplier.java:42)
	at com.epam.reportportal.testng.ReportPortalTestNGListener.<init>(ReportPortalTestNGListener.java:33)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:560)
	at org.testng.internal.InstanceCreator.newInstance(InstanceCreator.java:30)
	at org.testng.TestNG.addListeners(TestNG.java:964)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:924)
	at org.testng.TestNG.initializeEverything(TestNG.java:1012)
	at org.testng.remote.support.RemoteTestNG6_12.initialize(RemoteTestNG6_12.java:22)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:98)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by HardNorth** [comment]
@mohitb01 
Your dependency tree
```none
[INFO] org.insurity.glp.automation:TestNG:jar:0.0.1-SNAPSHOT
[INFO] +- junit:junit:jar:3.8.1:test
[INFO] +- org.seleniumhq.selenium:selenium-java:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-api:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-support:jar:3.14.0:compile
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.8.15:compile
[INFO] |  +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- com.google.guava:guava:jar:25.0-jre:compile
[INFO] |  |  +- org.checkerframework:checker-compat-qual:jar:2.0.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO] |  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:3.10.0:compile
[INFO] |  \- com.squareup.okio:okio:jar:1.14.1:compile
[INFO] +- com.epam.reportportal:agent-java-testng:jar:5.1.0-RC-1:compile
[INFO] |  +- com.epam.reportportal:client-java:jar:5.1.0-RC-5:compile
[INFO] |  |  +- io.reactivex.rxjava2:rxjava:jar:2.2.10:compile
[INFO] |  |  |  \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO] |  |  +- com.squareup.retrofit2:retrofit:jar:2.9.0:compile
[INFO] |  |  +- org.aspectj:aspectjrt:jar:1.9.2:compile
[INFO] |  |  +- com.squareup.retrofit2:converter-scalars:jar:2.9.0:runtime
[INFO] |  |  +- com.squareup.retrofit2:converter-jackson:jar:2.9.0:runtime
[INFO] |  |  +- com.squareup.retrofit2:adapter-rxjava2:jar:2.9.0:runtime
[INFO] |  |  +- com.squareup.okhttp3:logging-interceptor:jar:3.14.9:runtime
[INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.9.2:runtime
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- com.epam.reportportal:commons-model:jar:5.0.0:compile
[INFO] |  |  +- io.swagger:swagger-annotations:jar:1.5.24:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.1:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.1:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.10.1:compile
[INFO] |  |  +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.9:compile
[INFO] |  +- org.testng:testng:jar:7.1.0:compile
[INFO] |  |  +- com.beust:jcommander:jar:1.72:compile
[INFO] |  |  +- com.google.inject:guice:jar:no_aop:4.1.0:compile
[INFO] |  |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.21:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:runtime
[INFO] \- com.epam.reportportal:logger-java-log4j:jar:5.0.3:compile
[INFO]    +- log4j:log4j:jar:1.2.17:runtime
[INFO]    +- org.apache.logging.log4j:log4j-api:jar:2.13.0:runtime
[INFO]    \- org.apache.logging.log4j:log4j-core:jar:2.13.0:runtime
```
As you see your `selenium-java` dependency overrides `okhttp` with version 3.10.0. But ReportPortal client needs `okhttp` with version `3.11.0` as a minimum. So you need to update your `selenium-java` to at least version `3.141.0` (where `okhttp` version was update) or overwrite `okhttp` dependency to at least `3.11.0`.
