### ISSUE TITLE
Combine beforeMethod and afterMethod with Test

### ISSUE THREAD

**Issue by KacperWieczorek** [reportportal/agent-java-testNG#177]
**Considering a situation that we have following methods marked as beforeMethod:**
1. prepareSomeDataRequiredForTest
2. startWebDriver
3. goToTestedSystem
4. testPrecondition

**Then we have test method** 
5. doesSearchingForSomethingWork

**And following after methods**
6. closeWebDriver
7. createJiraTicket

Is it possible to have before and after methods merged into Test record in report portal without writing whole service by myself?

Having all those before and after methods as test steps would be ideal.

**Comment by HardNorth** [comment]
There is such functionality now. I future versions we are going to re-consider before/after method processing, but there is no ETA.

**Comment by KacperWieczorek** [comment]
If there is such functionality how do I access it? Is it a toggle or some parameter?

**Comment by HardNorth** [comment]
@KacperWieczorek, misprinted, sorry. "There is no functionality now".

**Comment by KacperWieczorek** [comment]
@HardNorth ah, Okay thanks for info tho. I'll try to tape something together. Thanks for the replies
