### ISSUE TITLE
Get Launch ID programmatically  

### ISSUE THREAD

**Issue by ASaiAnudeep** [reportportal/agent-java-testNG#180]
I am trying to get the launch id when the tests are running.

I have configured report-portal as a listener in my TestNG runner file.

```xml
<suite>
  <listeners>
    <listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener"></listener>
  <listeners>
  <test>
  ...
  </test>
</suite>
```

I tried to capture the launch id from the `reportportal.lock`. Which works fine in the Mac but fails in Windows machine with the following error.. 

```java
Path rp_path = Paths.get("reportportal.lock");
String content = Files.readString(rp_path,  StandardCharsets.US_ASCII);
```

```diff
- java.io.IOException: The process cannot access the file because another process has locked a portion of the file
``` 

Is there a way to get  Launch ID programmatically?

**Comment by HardNorth** [comment]
Please use this example: https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/logging/LaunchUrlLoggingTest.java

**Comment by HardNorth** [comment]
@ASaiAnudeep this file might be hard-locked, so you might get `IOException`.

**Comment by ASaiAnudeep** [comment]
Reading `.sync` is not raising any io exception in both mac and windows environments. 

```java
public static void saveReportPortalLaunchId() {
  Path rp_path = Paths.get("reportportal.sync");
  Path env_path = Paths.get(".env");
    try {
      if (Files.exists(rp_path)) {
        String content = Files.readString(rp_path, StandardCharsets.US_ASCII);
	String launch_id = content.split(":")[1];
	if (!Files.exists(env_path)) {
	  Files.createFile(env_path);
	}
	Files.writeString(env_path, "RP_LAUNCH_ID=" + launch_id);
       }
    } catch (IOException e) {
      e.printStackTrace();
    }
}
```
