### ISSUE TITLE
com.epam.reportportal.exception.InternalReportPortalClientException: Wait for Launch start timed out

### ISSUE THREAD

**Issue by bhagyaISS** [reportportal/agent-java-testNG#186]
**Describe the bug**

Hi Team,

I am using agent-java-testNG client with Selenium-Java framework and we have tests scheduled via Jenkins. Past few days, we are experiencing the below issue which leads to Jenkins jobs failure. These tests are running on cloud platform. 

![image](https://user-images.githubusercontent.com/109215760/178715381-fedb64b0-8eaa-4a04-b7e1-c2c78c337528.png)

I have attached stacktrace logs, [LaunchTimeOut-StacktraceLogs.txt](https://github.com/reportportal/agent-java-testNG/files/9101407/LaunchTimeOut-StacktraceLogs.txt)

 Kindly check the issue.

**Dependency versions**
agent-java-testng : 5.0.11
logger-java-logback: 4.0.5
logger-java-log4j: 5.0.3
selenium-java: 3.141.59
maven-compiler-plugin: 3.8.1
maven-surefire-plugin: 2.19.1
testng: 7.1.0

**Additional context**
I have tried to update the dependency as mentioned here https://github.com/reportportal/agent-java-testNG but no luck instead it has shown another error as below :
![image](https://user-images.githubusercontent.com/109215760/178717540-c4e633d9-6e93-43ae-9a30-438b747debbd.png)

**Comment by bhagyaISS** [comment]
Hi @HardNorth , Thank you for quick reply!

There is no launch for the above build on Report Portal UI.

And yes, I will take note of it - upgrading to the latest selenium version. Thank you for the suggestion!

Meanwhile, could you please help us to resolve the launch timeout issue? All I can say is that it is intermittent and we do not know the root cause.

**Comment by HardNorth** [comment]
@bhagyaISS I don't have enough information here. But having symptoms that something worked and then stopped without code updates I absolutely sure that the issue in the environment: SSL certificate expiration, new firewall rules, etc.

**Comment by bhagyaISS** [comment]
Hi,

We do not have SSL, firewall rules setup, and the issue is still happening.
Please let me know if you require additional information to debug issue further.

**Comment by HardNorth** [comment]
@bhagyaISS Could you please try setting `rp.client.join` property into `false`?

**Comment by HardNorth** [comment]
Abandoned
