### ISSUE TITLE
Test interrupt is reported on many tests execution

### ISSUE THREAD

**Issue by idan-marciano-jfrog** [reportportal/agent-java-testNG#188]
Recently i have integrated a very big suite (thousand of integration test) with report portal. While testing this integration i am experiencing lots of tests that are reported as interrupt and their run time is around 1:30 hours which is not the reality.
The test that were reported as interrupt actually passed but for some reason the connection was not close and i assume that some sort of timeout was reached or the launch was finished therefore report portal closed the open connection to the test and reported it as interrupt (not sure, those are assumptions).

1. How can i get to the root cause of a problem such as this?
2. Are there any configuration that i should tweak inorder to overcome this?

The tests are running on mvn command and i am using testng rp client 5.1.2 with rp server version 5.6.0

**Comment by HardNorth** [comment]
@idan-marciano-jfrog If the suite is really big, running in parallel, RP instance can really struggle to process it due to many reasons. In our install scripts we set configuration varables which are suitable for the most users, but they are not optimal for any particular use case. Usually every high-load pattern needs its tunning.

For the start you can tune HTTP timeouts and see if you get better results, see client configuration: https://github.com/reportportal/client-java#http-parameters

**Comment by idan-marciano-jfrog** [comment]
@HardNorth Thanks,
Regarding to the parallelism i am running all those tests on different execution so they are spreading out to multiple lunches
The symptom is this:
The test finished executing but it seems like the server still digest the data and from the UI its seems like its still in progress
![Screen Shot 2022-09-07 at 15 43 57](https://user-images.githubusercontent.com/68947907/188881489-cb215723-577b-4cea-9b71-c00a159760d1.png)

What i suspect is that maybe the server has reached a peak and its not able to process all the test 
Will those parameters help the put less load on the server:
rp.rx.buffer.size
rp.batch.size.logs

I see that in the doc they are suppose to be change together.Is there any thumb rule for increasing them both?

**Comment by HardNorth** [comment]
@idan-marciano-jfrog 
> I see that in the doc they are suppose to be change together.Is there any thumb rule for increasing them both?
Not really, `rp.rx.buffer.size` is mostly for those cases when someone is trying to push thousands of logs per second. Actually this parameter is growing automatically and the setting is needed just to speed up processing when amount of logs is that huge, that even automatic grow does not help.

As for `rp.batch.size.logs` it regulates the number of log items in one batch, which might help if you report a lot of small log items.

If you don't send big amounts of logs I would took a look into connection settings and server performance metrics. Does server struggles? Does DB request processing is fast enough? Does RabbitMq manage to store all items?

See:
https://reportportal.io/docs/Basic-monitoring-configuration
https://github.com/reportportal/documentation/blob/master/src/md/src/TipsAndTricks/PerfIssuesResolving.md

**Comment by HardNorth** [comment]
Answered
