### ISSUE TITLE
Retried test method not logged in RP with testng retry analyzer

### ISSUE THREAD

**Issue by suhaibm7** [reportportal/agent-java-testNG#192]
**Describe the bug**
I am using Report Portal Java Testng Agent Version 5.1.2 and Testng Version 7.5. We have retry analyzer in our test code and whenever our tests failed, they are retried one more time. The problem is in case a test is retried, report portal does not log the test case and reports on RP are all green with no failures but total number of test cases are less by the number of tests that are retried. One thing to note here is it does happen a lot of times but sometimes the retried methods are reported by RP and this happens only if it passes 2nd time.In case of failure it is never logged in RP. RP however has the indicator icon for retried methods every time test is retried . Testng produces the correct result with first run of the test case marked as skipped and the second one as pass/fail. I have uploaded images for reference. One where it is not logged after the retry and count is 1 less than actual and other when it has logged which had passed in the retry.

<img width="875" alt="Screenshot 2022-10-27 at 1 27 10 PM" src="https://user-images.githubusercontent.com/113339331/198226574-40118abd-324c-4771-9873-38213477bce4.png">

<img width="958" alt="Screenshot 2022-10-27 at 1 27 37 PM" src="https://user-images.githubusercontent.com/113339331/198227135-1021522b-a9ea-4f70-abe0-004559eabcac.png">

**Steps to Reproduce**
1. Run the suite with testng retry analyzer

**Expected behavior**
It should log everytime a test is retried in the reports

**Actual behavior**
Most of the time test is not logged in RP

**Dependency versions**
Java Testng agent version 5.1.2
logger-java-logback version 5.1.3
Testng version 7.5

**Additional context**

**Comment by HardNorth** [comment]
@suhaibm7 As for me everything works as designed, since the logic here to report one test no matter how many retires it has. Do you want to say that if all retries failed they are reported as additional test?

**Comment by HardNorth** [comment]
Abandoned
