### ISSUE TITLE
Find launch ID or complete URL of a launch after it is started

### ISSUE THREAD

**Issue by vallishk** [reportportal/agent-java-testNG#200]
When I use the testng client to start launches, I do not get the launch ID as a return value. What I would like to do is to be able to construct a URL for the particular launch that I can include in my slack messages. This will help in going directly to the report portal and land on the particular execution for debugging. For this, the launch ID needs to be returned somehow to the caller.

Additionally, if i can get a handle to the URL of every test case, it would do wonders in easing my debugging time.

**Comment by HardNorth** [comment]
There is `rp.launch.uuid.print` parameter in new agents: https://github.com/reportportal/client-java?tab=readme-ov-file#parameters
With which you can construct Launch URL as in example here: https://github.com/reportportal/examples-java/blob/a3edab9572ba5529b5bc1a5b6ff6c5ad8f6b17ae/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/logging/LaunchUrlLoggingTest.java#L46-L49#L46-L49
