### ISSUE TITLE
Logs duplicated when run tests in parallel

### ISSUE THREAD

**Issue by daroshchanka** [reportportal/agent-java-testNG#206]
**Describe the bug**
Works fine with `5.2.0`
Issue started from `5.3.1`, also reproduced with `5.4.1`.

**Steps to Reproduce**
1. testng 7.9.0 (maybe not important)
2. log4j2 2.22.0
3. have 5 test classes, each test class has same parent (BaseTest)
4. each test class has 1 test method
5. testng xml, parallel="tests" thread-count="5"
6. Report Portal listener defined in maven surefire plugin (same when define with annotation on Base class)
7. Run test xml via maven (or just from IDE if listener added on base test class)

**Expected behavior**
No any duplications for log records.

**Actual behavior**
logs duplicated in report portal for all kind of methods (test, configuration),
initially I see 2 duplications for each line, after some time (2-3min) it grows up to 10 or even more.

In system out
![image](https://github.com/reportportal/agent-java-testNG/assets/28945630/7f6e6f8a-b85d-4573-b856-d90d3bdb974d)

In RP
![image](https://github.com/reportportal/agent-java-testNG/assets/28945630/27adb399-7792-4b4d-bb59-ecd1e18b0bea)

**Dependency versions**
Server (own installation)
![image](https://github.com/reportportal/agent-java-testNG/assets/28945630/808bf79f-5c6a-47bc-98d5-d59d95d6dc38)

Client testng-agent
Works fine with `5.2.0`
Issue started from `5.3.1`, also reproduced in `5.4.1`.

**Additional context**

**Comment by HardNorth** [comment]
@daroshchanka, It's not TestNG issue, it server one, see here: https://github.com/reportportal/reportportal/issues/2148

Closing as duplicate.
