### ISSUE TITLE
Sending screenshots to Report Portal from project on docker 

### ISSUE THREAD

**Issue by urbando** [reportportal/agent-java-testNG#25]
Hi,

I have configured my testNG project for sending screenshots to Report Portal but it works only when I run the project locally on my Windows laptop.
Report Portal docker is deployed on linux server.

When I start the project with our Jenkins which is working on docker (the same server) I can see **RP_MESSAGE#BASE64# .. etc "** log in the proper form but file doesnt appear in ReportPortal.

Is there any addtional service, port settings I should apply to our Jenkins docker that it can send files to Report Portal?
I suppose there is some problem with communication between dockers?
How to check if there was a try of sending this file?

For runnig Report portal I have used default docker file just changed port to 8666.

[docker-compose (1).txt](https://github.com/reportportal/agent-java-testNG/files/1902661/docker-compose.1.txt)

Thanks,
Radek

**Comment by avarabyeu** [comment]
@urbando i guess you have different logging configuration for local and jenkins executions. Please, make sure reportportal's appender (whatever you use) is added to your logger configuration

**Comment by urbando** [comment]
Thank you for response.

All dependencies and config files are pushed to our repo so I don't think there can be any discrepancy between sources run locally and by jenkis. But I will double check it.
Is there any extra port for sending attachements /screenshot needed (maybe for mongoDB)?

**Comment by urbando** [comment]
Thank you for response.

All dependencies and config files are pushed to our repo so I don't think there can be any discrepancy between sources run locally and by jenkis. But I will double check it.
Is there any extra port for sending attachements /screenshot needed (maybe for mongoDB)?

**Comment by avarabyeu** [comment]
@urbando no, nothing is required

**Comment by avarabyeu** [comment]
Closing issue for now. Feel free if you have any questions or some assistance from our side is needed

**Comment by mohdsgithub** [comment]
> 
> 
> Thank you for response.
> 
> All dependencies and config files are pushed to our repo so I don't think there can be any discrepancy between sources run locally and by jenkis. But I will double check it.
> Is there any extra port for sending attachements /screenshot needed (maybe for mongoDB)?

Add dependency for cucumber:
<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber4</artifactId>
            <version>4.0.0</version>
        </dependency>

Then send screen shot file as:
ReportPortal.emitLog(testResult.getTestName(), "FAIL", Calendar.getInstance().getTime(), new File(fileLocation));
