### ISSUE TITLE
Launch not finished if testng SkipException thrown in Before/After methods

### ISSUE THREAD

**Issue by daroshchanka** [reportportal/agent-java-testNG#28]
#### Seems, SkipException in Before/After methods not handled correctly.
Problem actual for Before/After Suite, Before/After Test, Before/After Class, Before/After Method. Before/After Group not tested.

#### 2 Counfiguration methods duplicated

![image](https://user-images.githubusercontent.com/28945630/40665452-f1ac9488-6365-11e8-9ae1-372f12fc55c4.png)
[error.log](https://github.com/reportportal/agent-java-testNG/files/2048637/error.log)

![image](https://user-images.githubusercontent.com/28945630/40665727-b2c6e8a8-6366-11e8-87eb-6448afa4e0f8.png)

```
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.3</version> //6.11 the same
        </dependency>
```
### To Reproduce (groovy code)
```
import com.epam.reportportal.testng.ReportPortalTestNGListener
import org.testng.SkipException
import org.testng.annotations.BeforeClass
import org.testng.annotations.Listeners

@Listeners([ReportPortalTestNGListener])
class Test {

    @BeforeClass
    public void before(){
        throw new SkipException("text")
    }

    @org.testng.annotations.Test
    public void test1(){
        sleep(1000)
    }

    @org.testng.annotations.Test
    public void test2(){
        sleep(1000)
    }

    @org.testng.annotations.Test
    public void test3(){
        sleep(1000)
    }

}
```

**Comment by evjlobanova** [comment]
@avarabyeu could you please look at this issue?

**Comment by daroshchanka** [comment]
Hi, @avarabyeu.
I just removed line with startConfiguration https://github.com/reportportal/agent-java-testNG/blob/854985c1488e6548ce69fedf24a61472d3f35abb/src/main/java/com/epam/reportportal/testng/BaseTestNGListener.java#L124

**This fix works for us.** 
```
class MyReportPortalTestNGListener extends BaseTestNGListener {

    //static instance with lazy init
    private static final Supplier<ITestNGService> SERVICE = Suppliers.memoize(new Supplier<ITestNGService>() {
        @Override
        public ITestNGService get() {
            return new TestNGService()
        }
    });

    public MyReportPortalTestNGListener() {
        super(SERVICE.get())
    }
    
    @Override
    public void onConfigurationSkip(ITestResult testResult) {
        SERVICE.get().finishTestMethod(Statuses.SKIPPED, testResult)
    }
}
```

I checked fix under several projects, no side effects detected. 
Is this line needed? :)

**Comment by filland** [comment]
@daroshchanka 
Hello, i fixed the problem. 
Here is the branch with the fix  - https://github.com/reportportal/agent-java-testNG/tree/issue28
Could you try it with your tests ?

**Comment by daroshchanka** [comment]
@filland 
Works for me.

**Comment by filland** [comment]
@daroshchanka this fix is already in the latest published version

**Comment by NiliMe** [comment]
@filland It is not working for me on version 7.0.0-beta6.
SkipException on any Before method (before class, before suite, before method) makes the execution to stuck.

In the attached capture we can see that the method "getTmsVersionprintCurrentClass" (whice is annotated @BeforeClass) is stuck on InProgress, and so are all the Before methods after it (the methods "deleteAllMockDcs" & "temp" are @Test annotated but also didn't run properly.
![testng stuck](https://user-images.githubusercontent.com/4667329/57082492-81b39100-6cff-11e9-82de-39a980e0c515.PNG)

**Comment by filland** [comment]
@NiliMe this might happen since the agent using testng 6.14.3

**Comment by NiliMe** [comment]
@filland which agent is it? How can I upgrade the Testng version?
I'm running using Intellij (latest version) and surefire plugin (2.19.1)

**Comment by filland** [comment]
@NiliMe the latest version of reportportal testng agent developed using testng 6.14.3. I am going to investigate the reason why it does not work with testng 7.0.0.*. I also recommend you to not use 7th version of testng (if possible) since it is in beta stage.
