### ISSUE TITLE
Skipped Tests not showing when retry tests are included

### ISSUE THREAD

**Issue by pujaranichand** [reportportal/agent-java-testNG#31]
when i run the tests with the retry analyser, the skipped tests do not show , but when i run the tests without the retry analyser the skipped tests count shows on the report portal, can someone help here
![image](https://user-images.githubusercontent.com/24644827/48929376-3dc98e00-ef0e-11e8-93df-5024b05ab402.png)

**Comment by DzmitryHumianiuk** [comment]
@filland duplicate for #27 ?

**Comment by filland** [comment]
@DzmitryHumianiuk 

yes
