### ISSUE TITLE
ReportPortal Java Client is not affected by JVM Socks Proxy settings

### ISSUE THREAD

**Issue by kharytonenka** [reportportal/agent-java-testNG#4]
Access to Report Portal instance is established via socks proxy. Report Portal Java Client neither affected by OS socks proxy settings, no by JVM socks proxy settings, so it can't post data to Report Portal.
Please, add support of JVM socks proxy settings: 
```
-DsocksProxyHost=127.0.0.1
-DsocksProxyPort=1080 
```

More details here: https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

**Comment by avarabyeu** [comment]
@kharytonenka I've release BETA version of new client:

```
<dependency>
  <groupId>com.epam.reportportal</groupId>
  <artifactId>agent-java-testng</artifactId>
  <version>2.7.0-BETA-1</version>
</dependency>
```

This version support extension modules. It means you can override all beans defined in [ReportPortalClientModule](https://github.com/reportportal/client-java-core/blob/d93018d1a3526aac7e5b4ab823e414acf7565c1e/src/main/java/com/epam/reportportal/guice/ReportPortalClientModule.java)

To fix your issue, you can override HTTP client factory and add support of SOCKS proxy 'by hands' (Apache HTTP client does not support socks proxy out of the box).
Here is [example of extension module](https://gist.github.com/avarabyeu/102686781eda3f780e20064e6f940c6c)
To tell RP client about module, you need to provide it via JVM/env vars as follows:

```
-Drp.extension=FULL_PATH_TO_EXTENSION_MODULE_CLASS
```

@kharytonenka Please check it and let us know whether it helps

**Comment by kharytonenka** [comment]
@avarabyeu, many thanks! We will let you know soon whether it works for us

**Comment by salamatin** [comment]
@avarabyeu, we were able to use your example of extension module and access the RP instance via Socks proxy. Thanks a lot!

**Comment by avarabyeu** [comment]
@salamatin cool!
