### ISSUE TITLE
Add logs of After/Before methods into TestItem after in finished (aka Update Item after it closed)

### ISSUE THREAD

**Issue by yoavgeva** [reportportal/agent-java-testNG#43]
for example:
 1. have a test which run and finished (does not matter if passed) 
2. After test finished (can be lot of test after an such) I want to attach a log with video to it cause it created after the Test closes.

I am aware It can be done with API from your example, but how to get the ID of the correct Item not manually from the platform, but from the code.
also why not to Add a way to get the ID from ReportPortal Class and also update from there?

**Comment by DzmitryHumianiuk** [comment]
may have reference to https://github.com/reportportal/reportportal/issues/672

@yoavgeva reporting built on promises.
that means, that during execution, at the moment when object is not save in DB, but already created within execution thread, this object will have Promise, instead of real locator.
That was **first**.

**Second**, belongs to specifics of testNG and how it handles execution row of methods.
It doesn't share in context which `@After/@Before` method belongs to which `@Test`.

**Third**, in v4 we have restriction to log reports into closed test item. But it now removed with version 5.

@yoavgeva Do i understand you correctly, that you want to append logs and attachments from `@AfterMethod` into test item. which happen right before it?

**Comment by yoavgeva** [comment]
@DzmitryHumianiuk Yea I want to append logs and attachments into test item, which will happen after it was finished (the @Test ), it does not have to happen in @AfterMethod it can happen later (even while another test run or in @AfterSuite even), if I can get the promise for example, it can help me add logs/attachments with that test item whenever I want

**Comment by DzmitryHumianiuk** [comment]
@yoavgeva if you familiar with AspectJ, you can add mapping for `@Test` methods and append screenshooting functionality right on byte code of `@Test` method.

@Yumfriez will try to make example next week.

As for next releases, we plan to introduce tree view structure of tests.
this means, that you will see test case on the left, logs on the right.
and under the test case you will see related `@AfterMethod`. and just in one click you will reach details and logs in it.

**Comment by yoavgeva** [comment]
it's possible but my issue is not screenshot but video, and I can get video only after the object of webdriver is closed (it can be closed in after method or other method) screenshot you can take whenever you want. the idea here is to have capablitiles to add logs/attachment to a test item and not the related method for example aftermethod item, cause it's a debugging info that the tester need to see in context of the test item

**Comment by DzmitryHumianiuk** [comment]
@yoavgeva we have one idea for that, @Yumfriez will try to create example.

The idea is to keep static map of  `TestCaseId - uuid `
where `TestCaseId` will be the directly mentioned test case ID, thru annotation. Or automatically generated, based on method location, name and hashcode of paramentrs.

`uuid` - ID of element in data base, which can be referenced via API call.

API v5 will allow to report logs into finalized item.

once your execution completed, you can retrieve the map of cases/uuids and send attachment into required test case.

**Comment by yoavgeva** [comment]
@DzmitryHumianiuk sound awesome :), this was the part I was missing :)

**Comment by DzmitryHumianiuk** [comment]
@Yumfriez can you share example already?

**Comment by Yumfriez** [comment]
@yoavgeva https://github.com/reportportal/examples-java/blob/callback-examples/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/callback/CallbackReportingTest.java - example
Callback reporting wiki - https://github.com/reportportal/client-java/wiki/Default-reporting-flow

**Comment by yoavgeva** [comment]
awesome, will try it when we move to V5 hopefully soon
