### ISSUE TITLE
Creation of tags

### ISSUE THREAD

**Issue by karthikthe** [reportportal/agent-java-testNG#46]
To create tags, I had the following line in reportportal.properties
rp.tags = "smoke" "1.4.6"

Testng agent created one tag in RP combining both tags: "smoke" "1.4.6". I expected two tags: "smoke" and "1.4.6", not one. pytest created two tags for the same line. Having multiple tags (to describe what is being run) help find specific launch.
![testng](https://user-images.githubusercontent.com/51137695/58513874-8177ab80-816e-11e9-875d-ffab1954e3af.png)
![pytest](https://user-images.githubusercontent.com/51137695/58513881-889eb980-816e-11e9-9dfb-a71440638e19.png)

**Comment by arunkumar-muthusamy** [comment]
@karthikthe its semicolon separated.
rp.tags=smoke;1.4.6

**Comment by karthikthe** [comment]
Thanks @arunkumar-muthusamy. It worked.

rp.tags = smoke;1.4.6;"some other tag"
