### ISSUE TITLE
Reportportal with Selenium Grid

### ISSUE THREAD

**Issue by KunalShokeen432** [reportportal/agent-java-testNG#51]
This is not an issue. Just an understanding I need before integrating ReportPortal with Selenium Grid for parallel execution on different machines.

i.e...
If we have a host machine(from where execution is triggered and ReportPortal is hosted) and parallel execution takes place on multiple machines(nodes) via Selenium grid.

After execution does Reportportal create a single launch only on host for all test cases that executed on different nodes ?
All nodes execution --- > Single Launch
or do we have different launches for each execution on node respectively
Node 1 ---- > Launch 1
Node 2 ---- > Launch 2

If second case,then how can we combine multiple launches in RP in Java + TestNg ?

Thanks,
Kunal

**Comment by KunalShokeen432** [comment]
Can anyone please help with this ?

**Comment by KunalShokeen432** [comment]
Can someone please help with this ?

**Comment by arunkumar-muthusamy** [comment]
It will create one launch per test trigger. By nature, the reporting will be done by your test (which runs on a machine x, or may be you can call it as build server). Selenium grid-Nodes has nothing to do with reporting. 

Lets assume you use Java+TestNG with selenium grid, you will eventually run one TestNG.xml file. There is a listener for logback & log4j, whichever logger you are using, pick the respective listener and add it as your dependency. 

There is a full example project. Which might be helpful.

**Comment by HardNorth** [comment]
Examples are here: https://github.com/reportportal/examples-java
