### ISSUE TITLE
Duplicate tests in launch/lanch does not fininsh

### ISSUE THREAD

**Issue by Baivalr** [reportportal/agent-java-testNG#66]
I added reportportal to my project following the instructions here > https://github.com/reportportal/example-java-TestNG and using the @listeners annotation. The launches appear in reportportal and everything looks fine until the test runs end. The launch in RP never finishes and has to be forced to finish. The launches have duplicate suites, one of which finishes as expected, the other never finishes. This happens whether we run it locally/manually or use Jenkins. Does anyone have nay thoughts on why this is and how I can fix it? This is a selenium/java project ultimately running from a jenkins pipeline job.

Thx

**Comment by ihar-kahadouski** [comment]
It seems you have registered a few listeners. Check it please in pom.xml

**Comment by evjlobanova** [comment]
@Baivalr Does it help you?

**Comment by DzmitryHumianiuk** [comment]
@Baivalr please share you `pom.xml` and `suites.xml`
listener can also be defined there.

And plz let us know about the multi threading, do you use it?

**Comment by Baivalr** [comment]
no multithreading.
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>----</groupId>
		<artifactId>web-automation</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>s-release-regression</artifactId>

	<properties>
		<s-release-regression.skip.tests>true</s-release-regression.skip.tests>
		<skipTests>${s-release-regression.skip.tests}</skipTests>
	</properties>

	<build>
		<plugins>
			
			<plugin>
				<artifactId>maven-remote-resources-plugin</artifactId>
				<version>${version.plugin.remote-resources}</version>
				<executions>
					<execution>
						<id>process-remote-resources</id>
						<goals>
							<goal>process</goal>
						</goals>
						<configuration>
							<resourceBundles>
								<resourceBundle>---:web-automation-core:${project.version}</resourceBundle>
							</resourceBundles>
						</configuration>
					</execution>
				</executions>
			</plugin>

            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>RunTestSuite</id>
			<activation>
				<activeByDefault>false</activeByDefault>
				<property>
					<name>suite</name>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<version>${version.plugin.surefire}</version>
						<configuration>
                            <testFailureIgnore>true</testFailureIgnore>
							<suiteXmlFiles>
								<suiteXmlFile>src/test/resources/testng-suites/${suite}.xml</suiteXmlFile>
							</suiteXmlFiles>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

	<dependencies>

		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${version.dependency.testng}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.---</groupId>
			<artifactId>ats-page-objects</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>---</groupId>
			<artifactId>web-automation-core</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.1</version>
		</dependency>

		<dependency>
			<groupId>com.jayway.restassured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>2.8.0</version>
		</dependency>

		<dependency>
			<groupId>com.jayway.restassured</groupId>
			<artifactId>json-path</artifactId>
			<version>2.8.0</version>
		</dependency>

		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20151123</version>
		</dependency>
    </dependencies>

</project>
`
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="FastAdd" verbose="2" parallel="false" configfailurepolicy="continue">
	<groups>
		<run>
			<include name="FastAdd"></include>
		</run>
	</groups>
	<listeners>
		<listener class-name="com.---.automation.web.util.FirebaseReporter"></listener>
	</listeners>
	<test verbose="2" name="FastAdd-test">
		<packages>
			<package name="com.---.automation.regression.*"></package>
		</packages>
	</test>
</suite>`

**Comment by Baivalr** [comment]
and `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="FastAdd" verbose="2" parallel="false" configfailurepolicy="continue">
	<groups>
		<run>
			<include name="FastAdd"></include>
		</run>
	</groups>
	<listeners>
		<listener class-name="com.---.automation.web.util.FirebaseReporter"></listener>
	</listeners>
	<test verbose="2" name="FastAdd-test">
		<packages>
			<package name="com.---.automation.regression.*"></package>
		</packages>
	</test>
</suite>`

**Comment by ihar-kahadouski** [comment]
@Baivalr check please your XML files with sutes structure if they have `<listeners>` attribute

**Comment by evjlobanova** [comment]
@Baivalr Could you please tell us if it helped?

**Comment by Baivalr** [comment]
report portal listener is not defined in any suite xml.

**Comment by HardNorth** [comment]
obsolete
