### ISSUE TITLE
Cannot locate the classes that are mentioned here - ConfigurationModule & TestNGAgentModule

### ISSUE THREAD

**Issue by omkarnathsingh** [reportportal/agent-java-testNG#68]
Basically my problem is same as https://stackoverflow.com/questions/48899958/reportportal-wuth-testng-how-to-set-launch-name-during-run-time/49245585.
I tried code to override the UUID and Launch name from readme of https://github.com/reportportal/agent-java-testNG .

But Its throwing errors for classes not found. Where are these classes located?
ConfigurationModule, ReportPortalClientModule and TestNGAgentModule

**Comment by evjlobanova** [comment]
@omkarnathsingh which version of RP and agents do you use?

**Comment by evjlobanova** [comment]
try to use the latest version of RP - RC 6

**Comment by omkarnathsingh** [comment]
I am using agency-java version as 4.2.2 and my UI RP version is 4.3.0

**Comment by HardNorth** [comment]
@omkarnathsingh can you provide more specific example? How do you initialize the listener and which exact classes are not found? I can't recall these classes you listed.

**Comment by omkarnathsingh** [comment]
@HardNorth I am using this only sample code provided for params overriding https://github.com/reportportal/agent-java-testNG#code-example-how-to-overload-params-in-run-time

and it is unable to locate ConfigurationModule, ReportPortalClientModule and TestNGAgentModule

**Comment by HardNorth** [comment]
@omkarnathsingh That example is too outdated. I'm going to update it today.

**Comment by omkarnathsingh** [comment]
Thanks @HardNorth . Please update and share the URL. It would be helpful for everyone.

**Comment by HardNorth** [comment]
@omkarnathsingh Here:
V5: https://github.com/reportportal/agent-java-testNG
V4: https://github.com/reportportal/agent-java-testNG/tree/v4-hotfix

**Comment by omkarnathsingh** [comment]
Thanks @HardNorth  :)
