### ISSUE TITLE
Unable to update defect type in version 5

### ISSUE THREAD

**Issue by AutomateItEasyWay** [reportportal/agent-java-testNG#69]
Steps to reproduce:
1. Execute a test and make sure test run is reported in ReportPortal.
2. If any of the test in test run fails then you will see To Investigate under defect type under all launches on launches screen.
3. User should be able to click on To Investigate and then update values in Edit defect type dialog box.
4. I have tried the same scenario in version 4 of RP and it works perfectly fine. 

Attaching the screenshots, api responses that result in failure in version 5 of RP.

[RP_Bug_v4v5.docx](https://github.com/reportportal/agent-java-testNG/files/4051563/RP_Bug_v4v5.docx)

**Comment by evjlobanova** [comment]
@AutomateItEasyWay 
Hello, please update your version to RC 6, and try one more time
And check logs of service analyzer, if this issue will reproduce again

**Comment by omkarnathsingh** [comment]
@evjlobanova V5 has reached stable, so will agent-java won't get a stable release too?
