### ISSUE TITLE
Listeners order execution for RP agent

### ISSUE THREAD

**Issue by Zahorodnii** [reportportal/agent-java-testNG#72]
Steps:
1. Attach @Listeners annotation
2. Define example listeners in next order: @Listeners({ReportPortalTestNGListener.class, ScreenShooter.class})
3. In onTestFailure metod we have next line: this.testNGService.finishTestMethod("FAILED", testResult);
Due to listeners runing in random order, screenshot sometimes not attached to RP, becouse finishTestMethod runing before screenshot attach.  Nordstrom/TestNG-Foundation don't help, becouse now they have a bug with different versions of testNG and Nordstrom.
![зображення](https://user-images.githubusercontent.com/58936047/73281381-92465880-41f8-11ea-8f2f-f4b5084c8a88.png)

**Comment by HardNorth** [comment]
Need to discuss that internally.

**Comment by Zahorodnii** [comment]
> 
> 
> Need to discuss this internally first.

Ask @vadzim

**Comment by Zahorodnii** [comment]
Incorrect close, please reopen

**Comment by HardNorth** [comment]
Well, after months of thinking I believe this is not an our issue. TestNG doesn't provide any explicit method to implement listener execution order. Why we should implement it? We are not a test framework. There is a good answer from Cedric Beust to implement a listener of listeners by yourself and thus maintain the order of the listeners. I have nothing to add to it. Again, we are not a test framework to decide what to do for you.

Fell free to reopen if you have essential objections.
