### ISSUE TITLE
Parallel run. Logs and attachments are messed up between different threads

### ISSUE THREAD

**Issue by alex-i-rybkin** [reportportal/agent-java-testNG#76]
**Environment**
Server version: 5.0.0
Client version: BETA-8
Logger version: BETA-8

**Problem**
It seems that testng client incorrectly manages RP_ID for test items running in parallel. Having 2+ threads logs and attachments are posted to incorrect threads. 
![image](https://user-images.githubusercontent.com/30799266/74144775-070c9000-4c06-11ea-99ed-20793ec5ec61.png)

**How to reproduce**
Sample project that reproduces the issue: [rp-sample.zip](https://github.com/reportportal/agent-java-testNG/files/4180453/rp-sample.zip)
Usage: update reportportal.properties and run.

**Comment by HardNorth** [comment]
The fix is on its way: https://github.com/reportportal/client-java/pull/68

**Comment by alex-i-rybkin** [comment]
reportportal/client-java#68 fixes the issues. BETA-9 release should resolve the problem
