### ISSUE TITLE
Error Message: Incorrect Request. [Field 'type' shouldn't be null.] 

### ISSUE THREAD

**Issue by Skaramus1990** [reportportal/agent-java-testNG#77]
`com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'type' shouldn't be null.] 
Error Type: INCORRECT_REQUEST

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

XML suite name="Name" verbose="1" parallel="instances" thread-count="4"

testNG version: 7.0.0
agent-java-testng: 4.2.0
logger-java-logback: 4.0.5
RP version: API Service: 4.3.1

Have you any solution for that?

**Comment by HardNorth** [comment]
Well, Agent version 4.2.0 is not actually compatible with TestNG 7.0.0. Can you update to version 4.2.3?

**Comment by Skaramus1990** [comment]
> Well, Agent version 4.2.0 is not actually compatible with TestNG 7.0.0. Can you update on version 4.2.3?

![Capture](https://user-images.githubusercontent.com/30906401/74737485-04451700-5266-11ea-9690-343c1c2cd85a.PNG)

**Comment by HardNorth** [comment]
It should.

**Comment by Skaramus1990** [comment]
> It should. Please upgrade and try again.
versions for TestNG and Reportportal in to POM file.
![versions from POM](https://user-images.githubusercontent.com/30906401/76056578-0f978280-5f88-11ea-8ba5-f81db230ad86.PNG)

Screenshot with error
![error](https://user-images.githubusercontent.com/30906401/76056583-11614600-5f88-11ea-923f-2f3308d3dcfa.PNG)

**Comment by HardNorth** [comment]
What `mvn dependency:tree` says? Does it contains older version of TestNG?

**Comment by Skaramus1990** [comment]
> What `mvn dependency:tree` says? Does it contains older version of TestNG?

![Capture](https://user-images.githubusercontent.com/30906401/76410625-4cf17b00-63a1-11ea-9aa1-739fc51338c3.PNG)

No, it doesn't.

**Comment by HardNorth** [comment]
Have you implemented any hooks, extensions, etc?

**Comment by Skaramus1990** [comment]
> Have you implemented any hooks, extensions, etc?

only one listener.
`import com.codeborne.selenide.WebDriverRunner;
import com.epam.reportportal.testng.ReportPortalTestNGListener;
import com.google.common.base.Throwables;
import org.apache.logging.log4j.Level;
import org.testng.ITestResult;

import static com.codeborne.selenide.WebDriverRunner.url;

public class CustomReportPortalListener extends ReportPortalTestNGListener {

    @Override
    public void onTestFailure (ITestResult result) {
        logEverything(result);
        super.onTestFailure(result);
    }

    @Override
    public void onConfigurationFailure (ITestResult result) {
        logEverything(result);
        super.onConfigurationFailure(result);
    }

    private static void logEverything (ITestResult result) {
        result.setThrowable(result.getThrowable());
        if (WebDriverRunner.hasWebDriverStarted()) {
            String errorMsg = String.format("Test failed.%nURL: %s%nException: %s%nStack trace:%n%s", url(),
                                            result.getThrowable().getMessage(), Throwables.getStackTraceAsString(result.getThrowable()));
            SendScreenshot.with(errorMsg, Level.ERROR);
        }
    }
}`

**Comment by HardNorth** [comment]
Well, after some investigations, I can say that such error might happen when:
1) An unknown test method type coming to the RP listener, which wasn't described in this class: https://github.com/reportportal/agent-java-testNG/blob/develop/src/main/java/com/epam/reportportal/testng/TestMethodType.java
2) An exception happens inside custom RP listener

Despite the reason of that in the latest version I updated the agent in such a way to avoid test execution crush. But if you need to report methods of the unknown type, you need to find and send me its name, I try to add it into the class.

**Comment by HardNorth** [comment]
Abandoned
