### ISSUE TITLE
Logs are getting logged in wrong tests

### ISSUE THREAD

**Issue by omkarnathsingh** [reportportal/agent-java-testNG#79]
I am using agent-java-testNG v5.0.0-BETA-9 and RP versions Current version:API Service: 5.0.0;Index Service: 5.0.5;Authorization Service: 5.0.0;Service UI: 5.0.0;

I am using testng to run 6 TC in where classes are to be run in parallel. But when logs are getting logged in RP, they are all messed, they are getting logged in wrong Tests and sometimes all into 1. How can I make it log correctly in their seperate Tests. Can it be due to me setting "rp.reporting.async", "true"?

My log4j.xml file looks like this:

```<?xml version="1.0" encoding="UTF-8"?>
<Configuration
	packages="com.epam.ta.reportportal.log4j.appender" status="WARN">
	<Appenders>
		<ReportPortalLog4j2Appender
			name="ReportPortalLog4j2Appender">
			<PatternLayout pattern="%-5level - %msg%n%throwable" />
		</ReportPortalLog4j2Appender>
		<Console name="ConsoleAppender" target="SYSTEM_OUT">
			<PatternLayout pattern="%-5level - %msg%n%throwable" />
		</Console>
	</Appenders>
	<Loggers>
		<Root level="INFO">
			<AppenderRef ref="ConsoleAppender" />
			<AppenderRef ref="ReportPortalLog4j2Appender" />
		</Root>
		<Logger name="com.epam.reportportal.service" level="WARN"
			additivity="false">
			<AppenderRef ref="ReportPortalLog4j2Appender" />
		</Logger>
		<Logger name="com.epam.reportportal.utils" level="WARN"
			additivity="false">
			<AppenderRef ref="ReportPortalLog4j2Appender" />
		</Logger>
	</Loggers>
</Configuration>```

**Comment by HardNorth** [comment]
Please execute `mvn dependency:tree` or `gradlew dependencies` and ensure that there is no 5.0.0-BETA-8 dependencies. Because BETA-9 was release exactly to resolve this issue.

**Comment by omkarnathsingh** [comment]
Thanks, working fine now.
