### ISSUE TITLE
Java agent sends duplicate log entries to Report Portal

### ISSUE THREAD

**Issue by dkorobtsov** [reportportal/agent-java-testNG#8]
Environment:
agent-java-testng	3.0.3
logger-java-log4j	3.0.1
client-java 		3.0.1
RP version: 		3.0.1

Check attached screenshot:
![rp_dup](https://cloud.githubusercontent.com/assets/13999072/26672154/d6a73a52-46c0-11e7-8c7f-181838e880df.png)

**Comment by dkorobtsov** [comment]
@avarabyeu looks like regression, I've changed dependencies to older version - works perfect,

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>2.6.1</version>
        </dependency>

**Comment by avarabyeu** [comment]
Please, use the latest version of log4j integration.
        <version>2.6.1</version>
Latest versions can be found here:
https://rpstatus.herokuapp.com/versions
