### ISSUE TITLE
Can't change RP Launch name

### ISSUE THREAD

**Issue by Zahorodnii** [reportportal/agent-java-testNG#80]
![зображення](https://user-images.githubusercontent.com/58936047/74726973-106eab80-5249-11ea-93ee-5f135241c2a5.png)
![зображення](https://user-images.githubusercontent.com/58936047/74726993-195f7d00-5249-11ea-9ffd-1fe6f3f6d6cf.png)

TestNG Agent: BETA-9
Log4J2 Version: BETA-9

**Comment by Zahorodnii** [comment]
I found the problem, if in property file rp.project = example, then all ok, but if rp.project=example, then for rp it's problem

**Comment by Zahorodnii** [comment]
Problem with rp.rerun = true

**Comment by HardNorth** [comment]
Rerun is rerun, when you specify `rp.rerun = true` server searches for a previous run. If there is no such run then it fails. I don't see any issues here.
