### ISSUE TITLE
Problems with TestNG Retry functionality

### ISSUE THREAD

**Issue by Zahorodnii** [reportportal/agent-java-testNG#82]
TestNG supports retry functionality: [TestNG Retry](https://testng.org/doc/documentation-main.html#rerunning)
* `Problem with RP test statuses: when testNG rerun failed test, all reruned tests without last will have skipped status:`
![зображення](https://user-images.githubusercontent.com/58936047/75164075-e1fd3e80-5728-11ea-99b0-c8bd807951a5.png)
`But RP sometimes set another tests statuses:`
![зображення](https://user-images.githubusercontent.com/58936047/75164142-fd684980-5728-11ea-858c-c828a47442bf.png)
* `RP rerun functionality don't supports TestNG retry functionality, if we want to do smth like this:`
![зображення](https://user-images.githubusercontent.com/58936047/75164617-bc246980-5729-11ea-88e4-1842dba33be4.png)
`it will not work`

**Comment by HardNorth** [comment]
We never implemented any property reload "on the fly", so it actually works as expected. And rerun - it's Launch level feature, you have to specify that flag on a Launch start, not on items during an execution.
