### ISSUE TITLE
Report portal not showing results with java 11

### ISSUE THREAD

**Issue by AspireFbbRP** [reportportal/agent-java-testNG#85]
Hi team,
I've integrated report portal with my java-testNG framework. And I can see the results in my reportportal account of my execution.
Now I just updated my java version from java 1.8 to Java 11 in my machine and pom.xml. Now I'm not able to see my results in reportportal. Does reportportal supports java 11?

Please help me on this.

Thanks

**Comment by AspireFbbRP** [comment]
Still not fixed.
I installed Java 11 in my system.
When I try to execute my test case, an error throws as following
"Error: Could not create Java Virtual Machine"
"Error: A fatal exception has occured. Program will exit"

If I installed and set java class path to 1.8, Its working fine.
Only when installing Java 11 it throwing fatal error.
For my project I need java 11.

Please help me.

**Comment by HardNorth** [comment]
Can you provide more details, logs? Which exact JDK are you using?

**Comment by DzmitryHumianiuk** [comment]
@AspireFbbRP see above.

not sure it is a RP related issue.
Your JVM of version 11 can't start itself. You should fix your java 11, rather then RP
