### ISSUE TITLE
Error when throwing SkipException from BeforeClass method when using agent-java-testng

### ISSUE THREAD

**Issue by talgreen1** [reportportal/agent-java-testNG#87]
Hi,

When trying to throw skip exception from a BeforeClass method, there is an error in the Report Portal (See below).

We are using the Following:
TestNG Version: 6.11 (Happens also with 6.14.2)
Report Portal Version: 4.0.0
agent-java-testng version: 4.0.0

I’m attaching an example project - [skip.zip](https://github.com/reportportal/reportportal/files/1912408/skip.zip)

The stack trace is: 
`io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish test item is not allowed. Test item '5ad343722ab79c0001eb1646' has descendants with 'IN_PROGRESS' status. All descendants '[TestItemid='5ad343722ab79c0001eb1647', ...
`
Full stack trace attached: 
[Full Stack Trace.txt](https://github.com/reportportal/reportportal/files/1912567/Full.Stack.Trace.txt)

**Comment by Skaramus1990** [comment]
+1. I have at the same problem.

**Comment by HardNorth** [comment]
@Skaramus1990 RP5 designed specifically to avoid such issues, unless you migrate on it you should care about test items processing order by yourself.
