### ISSUE TITLE
Report portal is not working Fine with TestNG Parallel Mode

### ISSUE THREAD

**Issue by the-octopus** [reportportal/agent-java-testNG#96]
When Enable TestNG Parallel mode, the log messages are not assigned to its test node:

Assume we have 3 test methods [Test1() , Test2() , Test3()]
Enable Parallel Mode with methods mode and with 3 threads to let all test methods run in same time.
use the report ortal logger and listener to log test results. 
after execution , there will be 3 test cases nodes under the launch/suit/test.
but one test case has the log of other test cases and other test cases will be empty.

Any recommendations for the TestNG parallel mode ?

**Comment by evjlobanova** [comment]
@the-octopus do you read https://github.com/reportportal/client-java/wiki/How-to-aggregate-Multi-thread-process-execution-in-one-launch? Does it help?

**Comment by the-octopus** [comment]
@evjlobanova Thanks for your sharing, I tried the explained configurations , But unfortunately not solved the issue. Still Logs for Test1, comes in Test2 and etc..... 

Please is you have a good example for TestNG Parallel integration share.

**Comment by evjlobanova** [comment]
@HardNorth may be you can help @the-octopus ?

**Comment by the-octopus** [comment]
@evjlobanova @HardNorth , any updates please. Thanks.

**Comment by HardNorth** [comment]
@the-octopus Which version of TestNG agent are you using?

**Comment by the-octopus** [comment]
@HardNorth , Please find below my dependencies .

```
<dependency>
            <groupId>com.epam.reportportal</groupId>
            <!--             <groupId>com.github.reportportal</groupId>-->
            <artifactId>agent-java-testng</artifactId>
            <version>5.0.0-BETA-8</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <!--            <groupId>com.github.reportportal</groupId>-->
            <artifactId>logger-java-logback</artifactId>
            <version>5.0.0-BETA-8</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>5.0.0-BETA-8</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.testng/testng -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.1.0</version>
        </dependency>
```

**Comment by HardNorth** [comment]
@the-octopus please use **BETA-9** dependecncies.
@evjlobanova Looks like the best way is to delete old betas from bintray after each release to force people use the latest dependencies.

**Comment by the-octopus** [comment]
@HardNorth , Thanks for your updates, I did changed the dependencies as follow.

Parallel reporting issue Solved.

But Another Issue , or a feature was removed which , **Iterations grouping** , at **BETA-8**  the iterations of the same method are grouped under same method name, But with version **BETA-9** no grouping of the iterations of the same Test Method.

**Iterations / retries image:**
![image](https://user-images.githubusercontent.com/22466471/79066411-664b5700-7cc0-11ea-827c-c5e4638eab85.png)

**BETA-9 without grouping:**


![image](https://user-images.githubusercontent.com/22466471/79066440-972b8c00-7cc0-11ea-8cd6-f2e6e3353bb9.png)

        ```
<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>5.0.0-BETA-9</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>5.0.0-BETA-9</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.testng/testng -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.1.0</version>
        </dependency>
```

**Comment by HardNorth** [comment]
There is no iteration grouping feature at all. It was a bug which caused these iterations were counted as `retires`.  As you see they are signed as `retries`. There is a related documentation of TestNG: https://testng.org/doc/documentation-main.html#rerunning

So I count this as closed, you are free to open a new issue if you want to suggest this bug as a feature. We might take it into consideration.
